### ISSUE TITLE
There is a bug in the code

### ISSUE THREAD

**Issue by HarisaranG** [seshathilak/Mastermind-game-#4]
@seshathilak 

![Screenshot at 2019-05-25 15-22-37](https://user-images.githubusercontent.com/39427312/58367824-60f6e980-7f01-11e9-89e1-07c2a3ff4d48.png)
there is a error becoz sum of p and q should be 4 i.e total number of digits but it is showing as 6 which is wrong check out the game rules properly

**Comment by seshathilak** [comment]
Yeah , Now I hope its error free
